### PR TITLE
Adapt this session to the change from `∏` to `‖`

### LINKED ISSUE #42: Adapt this session to the change from `∏` to `‖`
The Þ-calculus now uses the big `‖` for its notation for `general_parallel`; the switch to this notation was made in input-output-hk/thorn-calculus#102. We shall adapt the `Network_Equivalences` session to this change in notation.

### PR DESCRIPTION
**Pull request by jeltsch**
This resolves #42.

### CODE REVIEW

**Comment by jeltsch** [comment]
The automated build is still not successful, but the remaining problems are unrelated to the topic of this pull request and will therefore be handled in a different one.

**Review by javierdiaz72 — DISMISSED** [review]
Looks good to me.

**Comment by jeltsch** [comment]
> Looks good to me.

But wasn’t good enough. :grin:

**Review by javierdiaz72 — APPROVED** [review]
Looks good to me.

**Pull request merged**
